### ISSUE TITLE
Incompatible with webpack 2

### ISSUE THREAD

**Issue by MarshallOfSound** [th0r/webpack-bundle-analyzer#49]
#### Issue description

Was working brilliantly till I attempted to update to WebPack 2.2.0

#### Technical info
* Webpack Bundle Analyzer version: 2.2.3
* Webpack version: 2.2.0
* Node.js version: 6.9.3
* npm/yarn version: 0.18.1 (yarn)
* OS: macOS

#### Debug info
How do you use this module? As CLI utility or as plugin?

Tried both, same result

If CLI, what command was used? (e.g. `webpack-bundle-analyzer -O path/to/stats.json`)

If plugin, what options were provided? (e.g. `new BundleAnalyzerPlugin({ analyzerMode: 'disabled', generateStatsFile: true })`)

No options, just the defaults

Can't generate stats.json as it blows up before then.

#### Error

```
Could't analyze webpack bundle:
TypeError: currentFolder.addModule is not a function
Could't find any javascript bundles in provided stats file
```

**Comment by valscion** [comment]
I don't think it is a compatibility problem with webpack 2.2.0, as @Koslun uses it and it works for him, right?

So there's something else to this. Are you able to create reproduction repository for your issue? Without some way of us being able to reproduce this error, there's little we can do.

**Comment by MarshallOfSound** [comment]
Even better I managed to track it down, not sure if you would accept this as a fix but a PR with what I hacked in to make it work is incoming 👍

**Comment by Koslun** [comment]
@valscion @MarshallOfSound If it is still relevant I can confirm that it is indeed working on webpack@2.2.1 using webpack-bundle-analyzer@2.2.3.

**Comment by valscion** [comment]
Thanks @Koslun, that is relieving to hear :)

**Comment by valscion** [comment]
Hey would you be able to get a stats.json out by running webpack itself with the `--stats` flag and piping the output to a file?

```
webpack --json > stats.json
```

This might work as it doesn't require this plugin to be present at all

**Comment by th0r** [comment]
I have a theory about the reason for this bug but I need stats file to prove it.
@MarshallOfSound Could you generate stats file with `webpack --json > stats.json` as @valscion suggested?

**Comment by michaek** [comment]
@th0r I'm running into the same issue, from the CLI. My `stats.json` seems pretty verbose to post here, so I was hoping to create a tiny example shortly.

**Comment by michaek** [comment]
I just realized that when I say "the same issue", I should be more explicit. All I'm seeing output when I run `webpack-bundle-analyzer stats.json dist` is "Could't find any javascript bundles in provided stats file".

**Comment by valscion** [comment]
A small reproduction case would be highly appreciated ☺️. The `stats.json` can be zipped and uploaded here, in case you are not able to create that tiny example.

It will contain your source codes, though.

**Comment by AvraamMavridis** [comment]
I am experiancing the same issue

```
Could't analyze webpack bundle:
TypeError: currentFolder.addModule is not a function
Could't find any javascript bundles in provided stats file
```

In webpack settings I have:

```
    devServer: {
      contentBase: path.join(__dirname, '../build'),
      compress: !isFastMode,
      port: 8000,
      clientLogLevel: 'info',
      historyApiFallback: true,
      stats: 'normal'
    },
    stats: 'normal',
```

**Comment by valscion** [comment]
@AvraamMavridis can you provide the stats.json for your case? Instructions are earlier in this thread

**Comment by AvraamMavridis** [comment]
@valscion  here you are 
[stats.json.zip](https://github.com/th0r/webpack-bundle-analyzer/files/819436/stats.json.zip)

**Comment by valscion** [comment]
Umm your `stats.json` only contains the text `undefined`. How did you generate it?

Did you try running

```
webpack --json > stats.json
```

**Comment by AvraamMavridis** [comment]
@valscion oh, will give it another try. And upload.

**Comment by pgoergler** [comment]
I have isssue too with webpack2.
````
webpack: Compiled successfully.
Could't analyze webpack bundle:
TypeError: Cannot read property 'raw' of undefined
Could't find any javascript bundles in provided stats file
````


[stats.json.zip](https://github.com/th0r/webpack-bundle-analyzer/files/824411/stats.json.zip)

**Comment by valscion** [comment]
Hiya @pgoergler! I'm not able to reproduce your error without having the built sources, too. Can you upload those with the stats file?

**Comment by pgoergler** [comment]
it happens when i use webpack-dev-server

**Comment by valscion** [comment]
Hmm, I don't think this plugin was intended to work with `webpack-dev-server`. Try using this plugin without the dev server.

**Comment by AvraamMavridis** [comment]
For me the issue was my order of plugins, putting bundle analyzer in the first place solves the problem.

**Comment by cchamberlain** [comment]
@valscion - I'm new to this plugin but what are the use cases for the default `analyzerMode` of `"server"` if its not meant to go with `webpack-dev-server`. Generally production builds run once and output static files to be served up by a process outside of `webpack` (so `server` option doesn't make much sense here to me).

**Comment by th0r** [comment]
@cchamberlain it doesn't pollute fs by generating report file.

**Comment by Kepro** [comment]
same issue here.. that stats.json is now 18.4 MB big :) before we join all aplications together it's working with webpack only with this settings that you can see down

> webpack-bundle-analyzer ./build/stats.json

Could't analyze webpack bundle:
TypeError: currentFolder.addModule is not a function
Could't find any javascript bundles in provided stats file

````
    new BundleAnalyzerPlugin({
      analyzerMode: 'disabled',
      generateStatsFile: true,
      // Excludes module sources from stats file so there won't be any sensitive data
      statsOptions: { source: false },
    }),
````

**Comment by valscion** [comment]
Ok great, I am able to reproduce the crash from your files, @Kepro. This will help in debugging this a lot :+1:

**Comment by jasonmacdonald** [comment]
Any update on this? I'm having the same issue as others. Seems to happen when I add a dynamic require statement.

**Comment by valscion** [comment]
Nope, no updates yet. If you're able to whip up a small reproduction repository showcasing this error it would help in coming up with a new test case and verify that #50 fixes this issue.

You could also try to come up with a test case for this. You'd need to add two files to `test/bundles` folder, one with the bundle file contents and the other with the expected JSON representation of the modules inside the bundle file.

This is a good, minimal example of what testing these looks like:

Source bundle: [validExtraBundleWithModulesAsArray.js](https://github.com/th0r/webpack-bundle-analyzer/blob/v2.3.1/test/bundles/validExtraBundleWithModulesAsArray.js)

```js
webpackJsonp([0,2],[,,function(t,e,r){'123'},,,function(t,e){'12345'},]);
```

Expected module output: [validExtraBundleWithModulesAsArray.modules.json](https://github.com/th0r/webpack-bundle-analyzer/blob/v2.3.1/test/bundles/validExtraBundleWithModulesAsArray.modules.json)

```js
{
  "modules": {
    "2": "{'123'}",
    "5": "{'12345'}"
  }
}
```

**Comment by th0r** [comment]
Should be fixes in `v2.4.0`

**Comment by thomasdavis** [comment]
@th0r oh my bad, I thought this lib was only at 2.1.x so thought that 2.4 was a while away. But nevermind I see where you are at now.
